export const CARD_WIKI_TEXT_BY_SLUG: Record<string, string> = {
  'abrasive': 'Sly. Gain 1 Dexterity. Gain 4 Thorns.',
  'accelerant': 'Poison is triggered 1 additional time.',
  'accuracy': 'Shivs deal 4 additional damage.',
  'acrobatics': 'Draw 3 cards. Discard 1 card.',
  'adaptive_strike': 'Deal 18 damage. Add a 0 Energy copy of this card into your Discard Pile.',
  'adrenaline': 'Gain 1 Energy. Draw 2 cards. Exhaust.',
  'afterimage': 'Whenever you play a card, gain 1 Block.',
  'afterlife': 'Summon 6. Exhaust.',
  'aggression': 'At the start of your turn, put a random Attack from your Discard Pile into your Hand and Upgrade it.',
  'alchemize': 'Procure a random potion. Exhaust.',
  'alignment': 'Gain 2 Star Energy.',
  'all_for_one': 'Deal 10 damage. Put ALL 0 Energy cards from your Discard Pile into your Hand.',
  'anger': 'Deal 6 damage. Add a copy of this card into your Discard Pile.',
  'anointed': 'Put every Rare card from your Draw Pile into your Hand. Exhaust.',
  'anticipate': 'Gain 3 Dexterity this turn.',
  'apotheosis': 'Innate. Upgrade ALL your cards. Exhaust.',
  'apparition': 'Ethereal. Gain 1 Intangible. Exhaust.',
  'armaments': 'Gain 5 Block. Upgrade a card in your Hand.',
  'arsenal': 'Innate. Whenever you create a card, gain 1 Strength.',
  'ascenders_bane': 'Unplayable. Ethereal. Eternal.',
  'ashen_strike': 'Deal 6 damage. Deals 3 additional damage for each card in your Exhaust Pile.',
  'assassinate': 'Innate. Deal 10 damage. Apply 1 Vulnerable. Exhaust.',
  'astral_pulse': 'Deal 14 damage to ALL enemies.',
  'automation': 'Every 10 cards you draw, gain 1 Colorless Energy.',
  'backflip': 'Gain 5 Block. Draw 2 cards.',
  'backstab': 'Innate. Deal 11 damage. Exhaust.',
  'bad_luck': 'Unplayable. At the end of your turn, if this is in your Hand, lose 13 HP. Eternal.',
  'ball_lightning': 'Deal 7 damage. Channel 1 Lightning.',
  'banshees_cry': 'Deal 33 damage to ALL enemies. Costs 2 Energy less for each Ethereal card played this combat.',
  'barrage': 'Deal 5 damage for each Channeled Orb.',
  'barricade': 'Block is not removed at the start of your turn.',
  'bash': 'Deal 8 damage. Apply 2 Vulnerable.',
  'battle_trance': 'Draw 3 cards. You cannot draw additional cards this turn.',
  'beacon_of_hope': 'Whenever you gain Block on your turn, other players gain half that much Block.',
  'beam_cell': 'Deal 3 damage. Apply 1 Vulnerable.',
  'beat_down': 'Play 3 random Attacks from your Discard Pile.',
  'beat_into_shape': 'Deal 5 damage. Forge 5. Forges an additional 5 for every other time you\'ve hit the enemy this turn.',
  'beckon': 'At the end of your turn, if this is in your Hand, lose 6 HP.',
  'begone': 'Deal 4 damage. Choose a card in your Hand to Transform into Minion Dive Bomb.',
  'believe_in_you': 'Another player gains 3 Colorless Energy.',
  'biased_cognition': 'Gain 4 Focus. At the start of your turn, lose 1 Focus.',
  'big_bang': 'Draw 1 card. Gain 1 Star Energy. Gain 1 Star Energy. Forge 5.',
  'black_hole': 'Whenever you spend or gain 1 Star Energy deal 3 damage to ALL enemies.',
  'blade_dance': 'Add 3 Shivs into your Hand. Exhaust.',
  'blade_of_ink': 'This turn, whenever you play an Attack, gain 2 Strength this turn.',
  'blight_strike': 'Deal 8 damage. Apply Doom equal to damage dealt.',
  'blood_wall': 'Lose 2 HP. Gain 16 Block.',
  'bloodletting': 'Lose 3 HP. Gain 2 Energy.',
  'bludgeon': 'Deal 32 damage.',
  'blur': 'Gain 5 Block. Block is not removed at the start of your next turn.',
  'body_slam': 'Deal damage equal to your Block.',
  'bodyguard': 'Summon 5.',
  'bolas': 'Deal 3 damage. At the start of your next turn, return this to your Hand.',
  'bombardment': 'Deal 18 damage. At the start of your turn, plays from the Exhaust Pile. Exhaust.',
  'bone_shards': 'If Osty is alive, he deals 9 damage to ALL enemies and you gain 9 Block. Osty dies.',
  'boost_away': 'Gain 6 Block. Add a Dazed into your Discard Pile.',
  'boot_sequence': 'Innate. Gain 10 Block. Exhaust.',
  'borrowed_time': 'Apply 3 Doom to yourself. Gain 1 Energy.',
  'bouncing_flask': 'Apply 3 Poison to a random enemy 3 times.',
  'brand': 'Lose 1 HP. Exhaust 1 card. Gain 1 Strength.',
  'break': 'Deal 20 damage. Apply 5 Vulnerable.',
  'breakthrough': 'Lose 1 HP. Deal 9 damage to ALL enemies.',
  'brightest_flame': 'Gain 2 Colorless Energy. Draw 2 cards. Lose 1 Max HP.',
  'bubble_bubble': 'If the enemy has Poison, apply 9 Poison.',
  'buffer': 'Prevent the next time you would lose HP.',
  'bulk_up': 'Lose 1 Orb Slot. Gain 2 Strength. Gain 2 Dexterity.',
  'bullet_time': 'You cannot draw additional cards this turn. ALL cards in your Hand are free to play this turn.',
  'bully': 'Deal 4 damage. Deals 2 additional damage for each Vulnerable on the enemy.',
  'bulwark': 'Gain 13 Block. Forge 10.',
  'bundle_of_joy': 'Add 3 random Colorless cards into your Hand. Exhaust.',
  'burn': 'Unplayable. At the end of your turn, if this is in your Hand, take 2 damage.',
  'burning_pact': 'Exhaust 1 card. Draw 2 cards.',
  'burst': 'This turn, your next Skill is played an extra time.',
  'bury': 'Deal 52 damage.',
  'byrd_swoop': 'Deal 14 damage.',
  'byrdonis_egg': 'Unplayable. Can be hatched at a Rest Site.',
  'calamity': 'Whenever you play an Attack, add a random Attack into your Hand.',
  'calcify': 'Osty\'s attacks deal 4 additional damage.',
  'calculated_gamble': 'Discard your Hand, then draw that many cards. Exhaust.',
  'call_of_the_void': 'At the start of your turn, add 1 random card into your Hand. It gains Ethereal.',
  'capacitor': 'Gain 2 Orb Slots.',
  'capture_spirit': 'Enemy loses 3 HP. Add 3 Souls into your Draw Pile.',
  'cascade': 'Play the top X cards of your Draw Pile.',
  'catastrophe': 'Play 2 random cards from your Draw Pile.',
  'celestial_might': 'Deal 6 damage 3 times.',
  'chaos': 'Channel 1 random Orb.',
  'charge': 'Choose 2 cards in your Draw Pile to Transform into Minion Strikes.',
  'charge_battery': 'Gain 7 Block. Next turn, gain 1 Energy.',
  'child_of_the_stars': 'Whenever you spend 1 Star Energy gain 2 Block for each 1 Star Energy spent.',
  'chill': 'Channel 1 Frost for each enemy. Exhaust.',
  'cinder': 'Deal 17 damage. Exhaust a random card in your hand.',
  'claw': 'Deal 3 damage. Increase the damage of ALL Claw cards by 2 this combat.',
  'cleanse': 'Summon 3. Exhaust 1 card from your Draw Pile.',
  'cloak_and_dagger': 'Gain 6 Block. Add 1 Shiv into your Hand.',
  'cloak_of_stars': 'Gain 7 Block.',
  'clumsy': 'Unplayable. Ethereal.',
  'cold_snap': 'Deal 6 damage. Channel 1 Frost.',
  'collision_course': 'Deal 9 damage. Add a Debris into your Hand.',
  'colossus': 'Gain 5 Block. You receive 50% less damage from Vulnerable enemies this turn.',
  'comet': 'Deal 33 damage. Apply 3 Weak. Apply 3 Vulnerable.',
  'compact': 'Gain 6 Block. Transform all Status cards in your Hand into Fuel.',
  'compile_driver': 'Deal 7 damage. Draw 1 card for each unique Orb you have.',
  'conflagration': 'Deal 8 damage to ALL enemies. Deals 2 additional damage for each other Attack you\'ve played this turn.',
  'conqueror': 'Forge 3. Sovereign Blade deals double damage to the enemy this turn.',
  'consuming_shadow': 'Channel 2 Dark. At the end of your turn, Evoke your leftmost Orb.',
  'convergence': 'Next turn, gain 1 Star Energy and 1 Star Energy. Retain your Hand this turn.',
  'coolant': 'At the start of your turn, gain 2 Block for each unique Orb you have.',
  'coolheaded': 'Channel 1 Frost. Draw 1 card.',
  'coordinate': 'Give another player 5 Strength this turn.',
  'corrosive_wave': 'Whenever you draw a card this turn, apply 3 Poison to ALL enemies.',
  'corruption': 'Skills cost 0 Energy. Whenever you play a Skill, Exhaust it.',
  'cosmic_indifference': 'Gain 6 Block. Put a card from your Discard Pile on top of your Draw Pile.',
  'countdown': 'At the start of your turn, apply 6 Doom to a random enemy.',
  'crash_landing': 'Deal 21 damage to ALL enemies. Fill your Hand with Debris.',
  'creative_ai': 'At the start of your turn, add a random Power into your Hand.',
  'crescent_spear': 'Deal 6 damage. Deals 2 additional damage for ALL your cards that have a 1 Star Energy cost.',
  'crimson_mantle': 'At the start of your turn, lose 1 HP and gain 8 Block.',
  'cruelty': 'Vulnerable enemies take an additional 25% damage.',
  'crush_under': 'Deal 7 damage to ALL enemies. All enemies lose 1 Strength this turn.',
  'curse_of_the_bell': 'Unplayable. Eternal.',
  'dagger_spray': 'Deal 4 damage to ALL enemies twice.',
  'dagger_throw': 'Deal 9 damage. Draw 1 card. Discard 1 card.',
  'danse_macabre': 'Whenever you play a card that costs 2 Energy or more, gain 3 Block.',
  'dark_embrace': 'Whenever a card is Exhausted, draw 1 card.',
  'dark_shackles': 'Enemy loses 9 Strength this turn. Exhaust.',
  'darkness': 'Channel 1 Dark. Trigger the passive ability of all Dark Orbs.',
  'dash': 'Gain 10 Block. Deal 10 damage.',
  'dazed': 'Unplayable. Ethereal.',
  'deadly_poison': 'Apply 5 Poison.',
  'death_march': 'Deal 8 damage. Deals 3 additional damage for each card drawn during your turn.',
  'deathbringer': 'Apply 21 Doom and 1 Weak to ALL enemies.',
  'deaths_door': 'Gain 6 Block. If you applied Doom this turn, gain Block 2 additional times.',
  'debilitate': 'Deal 7 damage. Vulnerable and Weak are twice as effective against the enemy for the next 3 turns.',
  'debris': 'Exhaust.',
  'debt': 'Unplayable. At the end of your turn, if this is in your Hand, lose 10 Gold.',
  'decay': 'Unplayable. At the end of your turn, if this is in your Hand, take 2 damage.',
  'decisions_decisions': 'Draw 3 cards. Choose a Skill in your Hand and play it 3 times. Exhaust.',
  'defend_defect': 'Gain 5 Block.',
  'defend_ironclad': 'Gain 5 Block.',
  'defend_necrobinder': 'Gain 5 Block.',
  'defend_regent': 'Gain 5 Block.',
  'defend_silent': 'Gain 5 Block.',
  'defile': 'Ethereal. Deal 13 damage.',
  'deflect': 'Gain 4 Block.',
  'defragment': 'Gain 1 Focus.',
  'defy': 'Ethereal. Gain 6 Block. Apply 1 Weak.',
  'delay': 'Gain 11 Block. Next turn, gain 1 Energy.',
  'demesne': 'Ethereal. At the start of your turn, gain 1 Energy and draw 1 additional card.',
  'demon_form': 'At the start of your turn, gain 2 Strength.',
  'demonic_shield': 'Lose 1 HP. Give another player Block equal to your Block. Exhaust.',
  'devastate': 'Deal 30 damage.',
  'devour_life': 'Whenever you play a Soul, Summon 1.',
  'dirge': 'Summon 3 X times. Add X Souls into your Draw Pile.',
  'discovery': 'Choose 1 of 3 random cards to add into your Hand. It costs 0 Colorless Energy this turn. Exhaust.',
  'disintegration': 'At the end of your turn, take 6 damage.',
  'dismantle': 'Deal 8 damage. If the enemy is Vulnerable, hits twice.',
  'dodge_and_roll': 'Gain 4 Block. Next turn, gain 4 Block.',
  'dominate': 'Gain 1 Strength for each Vulnerable on the enemy. Exhaust.',
  'double_energy': 'Double your Energy. Exhaust.',
  'doubt': 'Unplayable. At the end of your turn, if this is in your Hand, gain 1 Weak.',
  'drain_power': 'Deal 10 damage. Upgrade 2 random cards in your Discard Pile.',
  'dramatic_entrance': 'Innate. Deal 11 damage to ALL enemies. Exhaust.',
  'dredge': 'Put 3 cards from your Discard Pile into your Hand. Exhaust.',
  'drum_of_battle': 'Draw 2 cards. At the start of your turn, Exhaust the top card of your Draw Pile.',
  'dualcast': 'Evoke your rightmost Orb twice.',
  'dying_star': 'Ethereal. Deal 9 damage to ALL enemies. ALL enemies lose 9 Strength this turn.',
  'echo_form': 'Ethereal. The first card you play each turn is played an extra time.',
  'echoing_slash': 'Deal 10 damage to ALL enemies. Repeat this effect for each enemy killed.',
  'eidolon': 'Exhaust your Hand. If 9 cards were Exhausted this way, gain 1 Intangible.',
  'end_of_days': 'Apply 29 Doom to ALL enemies. Kill enemies with at least as much Doom as HP.',
  'energy_surge': 'ALL players gain 2 Energy. Exhaust.',
  'enfeebling_touch': 'Ethereal. Enemy loses 8 Strength this turn.',
  'enlightenment': 'Reduce the cost of ALL cards in your Hand to 1 this turn. Exhaust.',
  'enthralled': 'If this is in your Hand, it must be played before other cards. Eternal.',
  'entropy': 'At the start of your turn, Transform 1 card in your Hand.',
  'envenom': 'Whenever an Attack deals unblocked damage, apply 1 Poison.',
  'equilibrium': 'Gain 13 Block. Retain your Hand this turn.',
  'eradicate': 'Retain. Deal 11 damage X times.',
  'escape_plan': 'Draw 1 card. If you draw a Skill, gain 3 Block.',
  'eternal_armor': 'Gain 7 Plating.',
  'evil_eye': 'Gain 8 Block. Gain another 8 Block if you have Exhausted a card this turn.',
  'expect_a_fight': 'Gain 1 Energy for each Attack in your Hand.',
  'expertise': 'Draw cards until you have 6 in your Hand.',
  'expose': 'Remove all Artifact and Block from the enemy. Apply 2 Vulnerable. Exhaust.',
  'exterminate': 'Deal 3 damage 4 times to ALL enemies.',
  'falling_star': 'Deal 7 damage. Apply 1 Weak. Apply 1 Vulnerable.',
  'fan_of_knives': 'Shivs now hit ALL enemies. Add 4 Shivs into your Hand.',
  'fasten': 'Gain an additional 5 Block from Defend cards.',
  'fear': 'Ethereal. Deal 7 damage. Apply 1 Vulnerable.',
  'feed': 'Deal 10 damage. If Fatal, raise your Max HP by 3. Exhaust.',
  'feeding_frenzy': 'Gain 5 Strength this turn.',
  'feel_no_pain': 'Whenever a card is Exhausted, gain 3 Block.',
  'feral': 'The first time you play a 0 Energy Attack each turn, return it to your Hand.',
  'fetch': 'Osty deals 3 damage. If this is the first time this card has been played this turn, draw 1 card.',
  'fiend_fire': 'Exhaust your Hand. Deal 7 damage for each card Exhausted. Exhaust.',
  'fight_me': 'Deal 5 damage twice. Gain 2 Strength. The enemy gains 1 Strength.',
  'fight_through': 'Gain 13 Block. Add 2 Wounds into your Discard Pile.',
  'finesse': 'Gain 4 Block. Draw 1 card.',
  'finisher': 'Deal 6 damage for each Attack already played this turn.',
  'fisticuffs': 'Deal 7 damage. Gain Block equal to damage dealt.',
  'flak_cannon': 'Exhaust ALL your Status cards. Deal 8 damage to a random enemy for each card Exhausted.',
  'flame_barrier': 'Gain 12 Block. Whenever you are attacked this turn, deal 4 damage back.',
  'flanking': 'The enemy takes double damage from other players this turn.',
  'flash_of_steel': 'Deal 5 damage. Draw 1 card.',
  'flatten': 'Osty deals 12 damage. This card costs 0 Energy if Osty has attacked this turn.',
  'flechettes': 'Deal 5 damage for each Skill in your Hand.',
  'flick_flack': 'Sly. Deal 7 damage to ALL enemies.',
  'focused_strike': 'Deal 9 damage. Gain 1 Focus this turn.',
  'follow_through': 'Deal 6 damage to ALL enemies. If the last card you played this turn was a Skill, apply 1 Weak to ALL enemies.',
  'folly': 'Unplayable. Innate. Eternal.',
  'footwork': 'Gain 2 Dexterity.',
  'forbidden_grimoire': 'At the end of combat, you may remove a card from your Deck. Eternal.',
  'foregone_conclusion': 'Next turn, put 2 cards from your Draw Pile into your Hand.',
  'forgotten_ritual': 'If you Exhausted a card this turn, gain 3 Energy.',
  'frantic_escape': 'Get farther away. Increase Sandpit by 1. Increase the cost of this card by 1.',
  'friendship': 'Lose 2 Strength. Gain 1 Energy at the start of each turn.',
  'ftl': 'Deal 5 damage. If you have played fewer than 3 cards this turn, draw 1 card.',
  'fuel': 'Gain 1 Colorless Energy. Draw 1 card. Exhaust.',
  'furnace': 'At the start of your turn, Forge 4.',
  'fusion': 'Channel 1 Plasma.',
  'gamma_blast': 'Deal 13 damage. Apply 2 Weak. Apply 2 Vulnerable.',
  'gang_up': 'Deal 5 damage. Deals 5 additional damage for each time another player has attacked the enemy this turn.',
  'gather_light': 'Gain 7 Block. Gain 1 Star Energy.',
  'genesis': 'At the start of your turn, gain 2 Star Energy.',
  'genetic_algorithm': 'Gain 1 Block. Permanently increase this card\'s Block by 3. Exhaust.',
  'giant_rock': 'Deal 16 damage.',
  'glacier': 'Gain 6 Block. Channel 2 Frost.',
  'glasswork': 'Gain 5 Block. Channel 1 Glass.',
  'glimmer': 'Draw 3 cards. Put 1 card from your Hand on top of your Draw Pile.',
  'glimpse_beyond': 'ALL players add 3 Souls into their Draw Pile. Exhaust.',
  'glitterstream': 'Gain 11 Block. Next turn, gain 4 Block.',
  'glow': 'Gain 1 Star Energy. Draw 2 cards.',
  'go_for_the_eyes': 'Deal 3 damage. If the enemy intends to attack, apply 1 Weak.',
  'gold_axe': 'Deal damage equal to the number of cards played this combat.',
  'grand_finale': 'Can only be played if there are no cards in your Draw Pile. Deal 50 damage to ALL enemies.',
  'grapple': 'Deal 7 damage. Whenever you gain Block this turn, deal 5 damage to the enemy.',
  'grave_warden': 'Gain 8 Block. Add a Soul into your Draw Pile.',
  'graveblast': 'Deal 4 damage. Put a card from your Discard Pile into your Hand. Exhaust.',
  'greed': 'Unplayable. Eternal.',
  'guards': 'Transform any number of cards in your Hand into Minion Sacrifice. Exhaust.',
  'guiding_star': 'Deal 12 damage. Draw 2 cards.',
  'guilty': 'Unplayable. Removed from your Deck after 5 combats.',
  'gunk_up': 'Deal 4 damage 3 times. Add a Slimed into your Discard Pile.',
  'hailstorm': 'At the end of your turn, if you have Frost, deal 6 damage to ALL enemies.',
  'hammer_time': 'Whenever you Forge, all allies Forge as well.',
  'hand_of_greed': 'Deal 20 damage. If Fatal, gain 20 Gold.',
  'hand_trick': 'Gain 7 Block. Add Sly to a Skill in your Hand this turn.',
  'hang': 'Deal 10 damage. Double the damage ALL Hang cards deal to this enemy.',
  'haunt': 'Whenever you play a Soul, a random enemy loses 6 HP.',
  'havoc': 'Play the top card of your Draw Pile and Exhaust it.',
  'haze': 'Sly. Apply 4 Poison to ALL enemies.',
  'headbutt': 'Deal 9 damage. Put a card from your Discard Pile on top of your Draw Pile.',
  'heavenly_drill': 'Deal 8 damage X times. Double X if it\'s 4 or more.',
  'hegemony': 'Deal 15 damage. Next turn, gain 2 Star Energy.',
  'heirloom_hammer': 'Deal 17 damage. Choose a Colorless card in your Hand. Add a copy of that card into your Hand.',
  'helix_drill': 'Deal 3 damage for each 1 Energy previously spent this turn.',
  'hellraiser': 'Whenever you draw a card containing “Strike”, it is played against a random enemy.',
  'hemokinesis': 'Lose 2 HP. Deal 14 damage.',
  'hidden_cache': 'Gain 1 Star Energy. Next turn, gain 3 Star Energy.',
  'hidden_daggers': 'Discard 2 cards. Add 2 Shivs into your Hand.',
  'hidden_gem': 'A random card in your Draw Pile gains Replay 2.',
  'high_five': 'Osty deals 11 damage and applies 2 Vulnerable to ALL enemies.',
  'hologram': 'Gain 3 Block. Put a card from your Discard Pile into your Hand. Exhaust.',
  'hotfix': 'Gain 2 Focus this turn.',
  'howl_from_beyond': 'Deal 16 damage to ALL enemies. At the start of your turn, plays from the Exhaust Pile.',
  'huddle_up': 'ALL allies draw 2 cards.',
  'hyperbeam': 'Deal 26 damage to ALL enemies. Lose 3 Focus.',
  'i_am_invincible': 'Gain 9 Block. At the end of your turn, if this is on top of your Draw Pile, play it.',
  'ice_lance': 'Deal 19 damage. Channel 3 Frost.',
  'ignition': 'Another player Channels Plasma. Exhaust.',
  'impatience': 'If you have no Attacks in your Hand, draw 2 cards.',
  'impervious': 'Gain 30 Block. Exhaust.',
  'infection': 'Unplayable. At the end of your turn, if this is in your Hand, take 3 damage.',
  'infernal_blade': 'Add a random Attack into your Hand. It\'s free to play this turn. Exhaust.',
  'inferno': 'At the start of your turn, lose 1 HP. Whenever you lose HP on your turn, deal 6 damage to ALL enemies.',
  'infinite_blades': 'At the start of your turn, add 1 Shiv into your Hand.',
  'inflame': 'Gain 2 Strength.',
  'injury': 'Unplayable.',
  'intercept': 'Gain 9 Block. Redirect all incoming attacks that would be dealt to another player this turn to you.',
  'invoke': 'Next turn, Summon 2 and gain 2 Energy.',
  'iron_wave': 'Gain 5 Block. Deal 5 damage.',
  'iteration': 'The first time you draw a Status card each turn, draw 2 cards.',
  'jack_of_all_trades': 'Add 1 random Colorless card into your Hand. Exhaust.',
  'jackpot': 'Deal 25 damage. Add 3 random 0 Colorless Energy cards into your Hand.',
  'juggernaut': 'Whenever you gain Block, deal 5 damage to a random enemy.',
  'juggling': 'Add a copy of the third Attack you play each turn into your Hand.',
  'kingly_kick': 'Deal 24 damage. Whenever you draw this card, reduce its cost by 1.',
  'kingly_punch': 'Deal 8 damage. Whenever you draw this card, increase its damage by 3 this combat.',
  'knife_trap': 'Play every Shiv in your Exhaust Pile on the enemy.',
  'knockdown': 'Deal 10 damage. The enemy takes double damage from other players this turn.',
  'knockout_blow': 'Deal 30 damage. If this kills an enemy, gain 5 Star Energy.',
  'know_thy_place': 'Apply 1 Weak. Apply 1 Vulnerable. Exhaust.',
  'lantern_key': 'Unplayable. Unlocks a special event in the next Act.',
  'largesse': 'Another player adds 1 random Colorless card to their Hand.',
  'leading_strike': 'Deal 7 damage. Add 1 Shiv into your Hand.',
  'leap': 'Gain 9 Block.',
  'leg_sweep': 'Apply 2 Weak. Gain 11 Block.',
  'legion_of_bone': 'ALL players Summon 6. Exhaust.',
  'lethality': 'Ethereal. The first Attack each turn deals 50% additional damage.',
  'lift': 'Give another player 11 Block.',
  'lightning_rod': 'Gain 4 Block. At the start of the next 2 turns, Channel 1 Lightning.',
  'loop': 'At the start of your turn, trigger the passive ability of your rightmost Orb.',
  'luminesce': 'Retain. Gain 2 Colorless Energy. Exhaust.',
  'lunar_blast': 'Deal 4 damage for each Skill already played this turn.',
  'machine_learning': 'At the start of your turn, draw 1 additional card.',
  'make_it_so': 'Deal 6 damage. Every 3 Skills you play in a turn, put this into your Hand.',
  'malaise': 'Enemy loses X Strength. Apply X Weak. Exhaust.',
  'mangle': 'Deal 15 damage. Enemy loses 10 Strength this turn.',
  'manifest_authority': 'Gain 7 Block. Add 1 random Colorless card into your Hand.',
  'master_of_strategy': 'Draw 3 cards. Exhaust.',
  'master_planner': 'When you play a Skill, it gains Sly.',
  'maul': 'Deal 5 damage twice. Increase the damage of ALL Maul cards by 1 this combat.',
  'mayhem': 'At the start of your turn, play the top card of your Draw Pile.',
  'melancholy': 'Gain 13 Block. Reduce this card\'s cost by 1 Energy whenever ANYONE dies.',
  'memento_mori': 'Deal 8 damage. Deals 4 additional damage for each card discarded this turn.',
  'metamorphosis': 'Add 3 random Attacks into your Draw Pile. They\'re free to play this combat. Exhaust.',
  'meteor_shower': 'Deal 14 damage to ALL enemies. Apply 2 Weak and Vulnerable to ALL enemies.',
  'meteor_strike': 'Deal 24 damage. Channel 3 Plasma.',
  'mimic': 'Gain Block equal to the Block on another player. Exhaust.',
  'mind_blast': 'Innate. Deal damage equal to the number of cards in your Draw Pile.',
  'mind_rot': 'Draw 1 fewer card each turn.',
  'minion_dive_bomb': 'Deal 13 damage. Exhaust.',
  'minion_sacrifice': 'Gain 9 Block. Exhaust.',
  'minion_strike': 'Deal 7 damage. Draw 1 card. Exhaust.',
  'mirage': 'Gain Block equal to Poison on ALL enemies. Exhaust.',
  'misery': 'Deal 7 damage. Apply any debuffs on the enemy to ALL other enemies.',
  'modded': 'Gain 1 Orb Slot. Draw 1 card. Increase this card\'s cost by 1.',
  'molten_fist': 'Deal 10 damage. Double the enemy\'s Vulnerable. Exhaust.',
  'momentum_strike': 'Deal 10 damage. Reduce this card\'s cost to 0 Energy.',
  'monarchs_gaze': 'Whenever you attack an enemy, it loses 1 Strength this turn.',
  'monologue': 'Whenever you play a card this turn, gain 1 Strength this turn.',
  'multi_cast': 'Evoke your rightmost Orb X times.',
  'murder': 'Deal 1 damage. Deals 1 additional damage for each card drawn this combat.',
  'necro_mastery': 'Summon 5. Whenever Osty loses HP, ALL enemies lose that much HP as well.',
  'negative_pulse': 'Gain 5 Block. Apply 7 Doom to ALL enemies.',
  'neows_fury': 'Deal 10 damage. Put 2 random cards from your Discard Pile into your Hand. Exhaust.',
  'neurosurge': 'Gain 3 Energy. Draw 2 cards. At the start of your turn, apply 3 Doom to yourself.',
  'neutralize': 'Deal 3 damage. Apply 1 Weak.',
  'neutron_aegis': 'Gain 8 Plating.',
  'nightmare': 'Choose a card. Next turn, add 3 copies of that card into your Hand. Exhaust.',
  'no_escape': 'Apply 10 Doom, plus an additional 5 Doom for every 10 Doom already on this enemy.',
  'normality': 'Unplayable. You cannot play more than 3 cards this turn.',
  'nostalgia': 'The first Attack or Skill you play each turn is placed on top of your Draw Pile.',
  'noxious_fumes': 'At the start of your turn, apply 2 Poison to ALL enemies.',
  'null': 'Deal 10 damage. Apply 2 Weak. Channel 1 Dark.',
  'oblivion': 'Whenever you play a card this turn, apply 3 Doom to the enemy.',
  'offering': 'Lose 6 HP. Gain 2 Energy. Draw 3 cards. Exhaust.',
  'omnislice': 'Deal 8 damage. Damage ALL other enemies equal to the damage dealt.',
  'one_two_punch': 'This turn, your next Attack is played an extra time.',
  'orbit': 'Every 4 Star Energy you spend, gain 1 Star Energy.',
  'outbreak': 'Every 3 times you apply Poison, deal 11 damage to ALL enemies.',
  'overclock': 'Draw 2 cards. Add a Burn into your Discard Pile.',
  'pacts_end': 'Can only be played if you have 3 or more cards in your Exhaust Pile. Deal 17 damage to ALL enemies.',
  'pagestorm': 'Whenever you draw an Ethereal card, draw 1 card.',
  'pale_blue_dot': 'If you play 5 or more cards in a turn, draw 1 card at the start of your next turn.',
  'panache': 'Every time you play 5 cards in a single turn, deal 10 damage to ALL enemies.',
  'panic_button': 'Gain 30 Block. You cannot gain Block from cards for 2 turns. Exhaust.',
  'parry': 'Whenever you play Sovereign Blade, gain 6 Block.',
  'parse': 'Ethereal. Draw 3 cards.',
  'particle_wall': 'Gain 9 Block. Return this card to your Hand.',
  'patter': 'Gain 8 Block. Gain 2 Vigor.',
  'peck': 'Deal 2 damage 3 times.',
  'perfected_strike': 'Deal 6 damage. Deals 2 additional damage for ALL your cards containing “Strike”.',
  'phantom_blades': 'Shivs gain Retain. The first Shiv you play each turn deals 9 additional damage.',
  'photon_cut': 'Deal 10 damage. Draw 1 card. Put 1 card from your Hand on top of your Draw Pile.',
  'piercing_wail': 'ALL enemies lose 6 Strength this turn. Exhaust.',
  'pillage': 'Deal 6 damage. Draw cards until you draw a non-Attack card.',
  'pillar_of_creation': 'Whenever you create a card, gain 3 Block.',
  'pinpoint': 'Deal 17 damage. Costs 1 less 1 Energy for each Skill played this turn.',
  'poisoned_stab': 'Deal 6 damage. Apply 3 Poison.',
  'poke': 'Osty deals 6 damage.',
  'pommel_strike': 'Deal 9 damage. Draw 1 card.',
  'poor_sleep': 'Unplayable. Retain.',
  'pounce': 'Deal 12 damage. The next Skill you play costs 0 Energy.',
  'precise_cut': 'Deal 13 damage. Deals 2 less damage for each other card in your Hand.',
  'predator': 'Deal 15 damage. Next turn, draw 2 cards.',
  'prep_time': 'At the start of your turn, gain 4 Vigor.',
  'prepared': 'Draw 1 card. Discard 1 card.',
  'primal_force': 'Transform all Attacks in your Hand into Giant Rock.',
  'production': 'Gain 2 Colorless Energy. Exhaust.',
  'prolong': 'Next turn, gain Block equal to your current Block. Exhaust.',
  'prophesize': 'Draw 6 cards.',
  'protector': 'Osty deals 10 damage. Deals additional damage equal to Osty\'s Max HP.',
  'prowess': 'Gain 1 Strength. Gain 1 Dexterity.',
  'pull_aggro': 'Summon 4. Gain 7 Block.',
  'pull_from_below': 'Deal 5 damage for each Ethereal card played this combat.',
  'purity': 'Retain. Exhaust up to 3 cards in your Hand. Exhaust.',
  'putrefy': 'Apply 2 Weak. Apply 2 Vulnerable. Exhaust.',
  'pyre': 'Gain 1 Energy at the start of each turn.',
  'quadcast': 'Evoke your rightmost Orb 4 times.',
  'quasar': 'Choose 1 of 3 random Colorless cards to add into your Hand.',
  'radiate': 'Deal 3 damage to ALL enemies for each 1 Star Energy gained this turn.',
  'rage': 'Whenever you play an Attack this turn, gain 3 Block.',
  'rainbow': 'Channel 1 Lightning. Channel 1 Frost. Channel 1 Dark. Exhaust.',
  'rally': 'ALL players gain 12 Block.',
  'rampage': 'Deal 9 damage. Increase this card\'s damage by 5 this combat.',
  'rattle': 'Osty deals 7 damage. Hits an additional time for each other time he has attacked this turn.',
  'reanimate': 'Summon 20. Exhaust.',
  'reap': 'Retain. Deal 27 damage.',
  'reaper_form': 'Whenever Attacks deal damage, they also apply that much Doom.',
  'reave': 'Deal 9 damage. Add a Soul into your Draw Pile.',
  'reboot': 'Shuffle ALL your cards into your Draw Pile. Draw 4 cards. Exhaust.',
  'refine_blade': 'Forge 6. Next turn, gain 1 Star Energy.',
  'reflect': 'Gain 17 Block. Blocked attack damage is reflected to your attacker this turn.',
  'reflex': 'Sly. Draw 2 cards.',
  'refract': 'Deal 9 damage twice. Channel 2 Glass.',
  'regret': 'Unplayable. At the end of your turn, if this is in your Hand, lose 1 HP for each card in your Hand.',
  'relax': 'Gain 15 Block. Next turn, draw 2 cards and gain 2 Colorless Energy. Exhaust.',
  'rend': 'Deal 15 damage. Deals 5 additional damage for each unique debuff on the enemy.',
  'resonance': 'Gain 1 Strength. ALL enemies lose 1 Strength.',
  'restlessness': 'Retain. If your Hand is empty, draw 2 cards and gain 2 Colorless Energy.',
  'ricochet': 'Sly. Deal 3 damage to a random enemy 4 times.',
  'right_hand_hand': 'Osty deals 4 damage. Whenever you play a card that costs 2 Energy or more, return this to your Hand from the Discard Pile.',
  'rip_and_tear': 'Deal 7 damage to a random enemy twice.',
  'rocket_punch': 'Deal 13 damage. Draw 1 card. When a Status card is created, reduce this card\'s cost to 0 Energy this turn.',
  'rolling_boulder': 'At the start of your turn, deal 5 damage to ALL enemies and increase this damage by 5.',
  'royal_gamble': 'Gain 9 Star Energy. Exhaust.',
  'royalties': 'At the end of combat, gain 30 Gold.',
  'rupture': 'Whenever you lose HP on your turn, gain 1 Strength.',
  'sacrifice': 'Retain. If Osty is alive, he dies and you gain Block equal to double his Max HP.',
  'salvo': 'Deal 12 damage. Retain your Hand this turn.',
  'scavenge': 'Exhaust a card. Next turn, gain 2 Energy.',
  'scourge': 'Apply 13 Doom. Draw 1 card.',
  'scrape': 'Deal 7 damage. Draw 4 cards. Discard all cards drawn this way that do not cost 0 Energy.',
  'scrawl': 'Draw cards until your Hand is full. Exhaust.',
  'sculpting_strike': 'Deal 8 damage. Add Ethereal to a card in your Hand.',
  'seance': 'Ethereal. Transform a card in your Draw Pile into Soul.',
  'second_wind': 'Exhaust all non-Attack cards in your Hand. Gain 5 Block for each card Exhausted.',
  'secret_technique': 'Put a Skill from your Draw Pile into your Hand. Exhaust.',
  'secret_weapon': 'Put an Attack from your Draw Pile into your Hand. Exhaust.',
  'seeker_strike': 'Deal 6 damage. Choose 1 of 3 cards in your Draw Pile to add into your Hand.',
  'seeking_edge': 'Forge 7. Sovereign Blade now deals damage to ALL enemies.',
  'sentry_mode': 'At the start of your turn, add 1 Sweeping Gaze into your Hand.',
  'serpent_form': 'Whenever you play a card, deal 4 damage to a random enemy.',
  'setup_strike': 'Deal 7 damage. Gain 2 Strength this turn.',
  'seven_stars': 'Deal 7 damage to ALL enemies 7 times.',
  'severance': 'Deal 13 damage. Add a Soul into your Draw Pile, Hand, and Discard Pile.',
  'shadow_shield': 'Gain 11 Block. Channel 1 Dark.',
  'shadow_step': 'Discard your Hand. Next turn, Attacks deal double damage.',
  'shadowmeld': 'Double your Block gain this turn.',
  'shame': 'Unplayable. At the end of your turn, if this is in your Hand, gain 1 Frail.',
  'shared_fate': 'Lose 2 Strength. Enemy loses 2 Strength. Exhaust.',
  'shatter': 'Deal 11 damage to ALL enemies. Evoke all of your Orbs.',
  'shining_strike': 'Deal 8 damage. Gain 2 Star Energy. Put this card on top of your Draw Pile.',
  'shiv': 'Deal 4 damage. Exhaust.',
  'shockwave': 'Apply 3 Weak and Vulnerable to ALL enemies. Exhaust.',
  'shroud': 'Whenever you apply Doom, gain 2 Block.',
  'shrug_it_off': 'Gain 8 Block. Draw 1 card.',
  'sic_em': 'Osty deals 5 damage. Whenever Osty hits this enemy this turn, Summon 2.',
  'signal_boost': 'The next Power you play is played an additional time. Exhaust.',
  'skewer': 'Deal 7 damage X times.',
  'skim': 'Draw 3 cards.',
  'sleight_of_flesh': 'Whenever you apply a debuff to an enemy, they take 9 damage.',
  'slice': 'Deal 6 damage.',
  'slimed': 'Draw 1 card. Exhaust.',
  'sloth': 'You cannot play more than 3 cards each turn.',
  'smokestack': 'Whenever you create a Status, deal 5 damage to ALL enemies.',
  'snakebite': 'Retain. Apply 7 Poison.',
  'snap': 'Osty deals 7 damage. Add Retain to a card in your Hand.',
  'sneaky': 'Sly. Whenever another player attacks an enemy, gain 1 Block.',
  'solar_strike': 'Deal 8 damage. Gain 1 Star Energy.',
  'soot': 'Unplayable.',
  'soul': 'Draw 2 cards. Exhaust.',
  'soul_storm': 'Deal 9 damage. Deals 2 additional damage for each Soul in your Exhaust Pile.',
  'sovereign_blade': 'Retain. Deal 10 damage.',
  'sow': 'Retain. Deal 8 damage to ALL enemies.',
  'spectrum_shift': 'At the start of your turn, add 1 random Colorless card into your Hand.',
  'speedster': 'Whenever you draw a card during your turn, deal 2 damage to ALL enemies.',
  'spinner': 'At the start of your turn, Channel 1 Glass.',
  'spirit_of_ash': 'Whenever you play an Ethereal card, gain 4 Block.',
  'spite': 'Deal 6 damage. If you lost HP this turn, draw 1 card.',
  'splash': 'Choose 1 of 3 random Attacks from another character to add into your Hand. It\'s free to play this turn.',
  'spoils_map': 'Unplayable. Marks a site of 600 extra Gold in the next Act.',
  'spoils_of_battle': 'Forge 10.',
  'spore_mind': 'Exhaust.',
  'spur': 'Retain. Summon 3. Osty heals 5 HP.',
  'squash': 'Deal 10 damage. Apply 2 Vulnerable.',
  'squeeze': 'Osty deals 25 damage. Deals 5 additional damage for ALL your other Osty Attacks.',
  'stampede': 'At the end of your turn, 1 random Attack in your Hand is played against a random enemy.',
  'stardust': 'Deal 5 damage to a random enemy X times.',
  'stoke': 'Exhaust your Hand. Draw a card for each card Exhausted. Exhaust.',
  'stomp': 'Deal 12 damage to ALL enemies. Costs 1 less 1 Energy for each Attack played this turn.',
  'stone_armor': 'Gain 4 Plating.',
  'storm': 'Whenever you play a Power, Channel 1 Lightning.',
  'storm_of_steel': 'Discard your Hand. Add 1 Shiv into your Hand for each card discarded.',
  'strangle': 'Deal 8 damage. Whenever you play a card this turn, the enemy loses 2 HP.',
  'stratagem': 'Whenever you shuffle your Draw Pile, choose a card from it to put into your Hand.',
  'strike_defect': 'Deal 6 damage.',
  'strike_ironclad': 'Deal 6 damage.',
  'strike_necrobinder': 'Deal 6 damage.',
  'strike_regent': 'Deal 6 damage.',
  'strike_silent': 'Deal 6 damage.',
  'subroutine': 'Whenever you play a Power, gain 1 Energy.',
  'sucker_punch': 'Deal 8 damage. Apply 1 Weak.',
  'summon_forth': 'Forge 8. Put Sovereign Blade into your Hand from anywhere.',
  'sunder': 'Deal 24 damage. If this kills an enemy, gain 3 Energy.',
  'supercritical': 'Gain 4 Energy. Exhaust.',
  'supermassive': 'Deal 5 damage. Deals 3 additional damage for each card you created this combat.',
  'suppress': 'Innate. Deal 11 damage. Apply 3 Weak.',
  'survivor': 'Gain 8 Block. Discard 1 card.',
  'sweeping_beam': 'Deal 6 damage to ALL enemies. Draw 1 card.',
  'sweeping_gaze': 'Ethereal. Osty deals 10 damage to a random enemy. Exhaust.',
  'sword_boomerang': 'Deal 3 damage to a random enemy 3 times.',
  'sword_sage': 'Sovereign Blade now hits an additional time.',
  'synchronize': 'Gain 2 Focus this turn for each unique Orb you have. Exhaust.',
  'synthesis': 'Deal 12 damage. The next Power you play costs 0 Energy.',
  'tactician': 'Sly. Gain 1 Energy.',
  'tag_team': 'Deal 11 damage. The next Attack another player plays on the enemy is played an extra time.',
  'tank': 'Take double damage from enemies. Allies take half damage from enemies.',
  'taunt': 'Gain 7 Block. Apply 1 Vulnerable.',
  'tear_asunder': 'Deal 5 damage. Hits an additional time for each time you lost HP this combat.',
  'tempest': 'Channel X Lightning.',
  'terraforming': 'Gain 6 Vigor.',
  'tesla_coil': 'Deal 3 damage. Trigger all Lightning against the enemy.',
  'the_bomb': 'At the end of 3 turns, deal 40 damage to ALL enemies.',
  'the_gambit': 'Gain 50 Block. If you take unblocked attack damage this combat, die.',
  'the_hunt': 'Deal 10 damage. If Fatal, gain an additional card reward. Exhaust.',
  'the_scythe': 'Deal 13 damage. Permanently increase this card\'s damage by 3. Exhaust.',
  'the_sealed_throne': 'Whenever you play a card, gain 1 Star Energy.',
  'the_smith': 'Forge 30.',
  'thinking_ahead': 'Draw 2 cards. Put 1 card from your Hand on top of your Draw Pile. Exhaust.',
  'thrash': 'Deal 4 damage twice. Exhaust a random Attack in your Hand and add its damage to this card.',
  'thrumming_hatchet': 'Deal 11 damage. At the start of your next turn, return this to your Hand.',
  'thunder': 'Whenever you Evoke Lightning, deal 6 damage to each enemy hit.',
  'thunderclap': 'Deal 4 damage and apply 1 Vulnerable to ALL enemies.',
  'times_up': 'Deal damage equal to the enemy\'s Doom. Exhaust.',
  'tools_of_the_trade': 'At the start of your turn, draw 1 card and discard 1 card.',
  'toric_toughness': 'Gain 5 Block. Gain 5 Block at the start of the next 2 turns.',
  'toxic': 'At the end of your turn, if this is in your Hand, take 5 damage. Exhaust.',
  'tracking': 'Weak enemies take double damage from Attacks.',
  'transfigure': 'Add Replay to a card in your Hand. It costs an extra 1 Energy. Exhaust.',
  'trash_to_treasure': 'Whenever you create a Status card, Channel 1 random Orb.',
  'tremble': 'Apply 2 Vulnerable. Exhaust.',
  'true_grit': 'Gain 7 Block. Exhaust 1 card at random.',
  'turbo': 'Gain 2 Energy. Add a Void into your Discard Pile.',
  'twin_strike': 'Deal 5 damage twice.',
  'tyranny': 'At the start of your turn, draw 1 card and Exhaust 1 card from your Hand.',
  'ultimate_defend': 'Gain 11 Block.',
  'ultimate_strike': 'Deal 14 damage.',
  'undeath': 'Gain 7 Block. Add a copy of this card into your Discard Pile.',
  'unleash': 'Osty deals 6 damage. Deals additional damage equal to Osty\'s current HP.',
  'unmovable': 'The first time you gain Block from a card each turn, double the amount gained.',
  'unrelenting': 'Deal 12 damage. The next Attack you play costs 0 Energy.',
  'untouchable': 'Sly. Gain 9 Block.',
  'up_my_sleeve': 'Add 3 Shivs into your Hand. Reduce this card\'s cost by 1.',
  'uppercut': 'Deal 13 damage. Apply 1 Weak. Apply 1 Vulnerable.',
  'uproar': 'Deal 5 damage twice. Play a random Attack from your Draw Pile.',
  'veilpiercer': 'Deal 10 damage. The next Ethereal card you play costs 0 Energy.',
  'venerate': 'Gain 2 Star Energy.',
  'vicious': 'Whenever you apply Vulnerable, draw 1 card.',
  'void': 'Unplayable. Ethereal. Whenever you draw this card, lose 1 Colorless Energy.',
  'void_form': 'End your turn. The first 2 cards you play each turn are free to play.',
  'volley': 'Deal 10 damage to a random enemy X times.',
  'voltaic': 'Channel Lightning equal to the Lightning already Channeled this combat. Exhaust.',
  'waste_away': 'Gain 1 less 1 Colorless Energy per turn.',
  'well_laid_plans': 'At the end of your turn, Retain up to 1 card.',
  'whirlwind': 'Deal 5 damage to ALL enemies X times.',
  'whistle': 'Deal 33 damage. Stun the enemy. Exhaust.',
  'white_noise': 'Add a random Power into your Hand. It\'s free to play this turn. Exhaust.',
  'wish': 'Put a card from your Draw Pile into your Hand. Exhaust.',
  'wisp': 'Gain 1 Energy. Exhaust.',
  'wound': 'Unplayable.',
  'wraith_form': 'Gain 2 Intangible. At the start of your turn, lose 1 Dexterity.',
  'writhe': 'Unplayable. Innate.',
  'wrought_in_war': 'Deal 7 damage. Forge 5.',
  'zap': 'Channel 1 Lightning.'
};
