/* eslint-disable */
// Auto-generated by scripts/generate-relic-potion-data.mjs
// Source: /Users/jiaojian/Desktop/sts2/sts2整理过的文件/sts2_site_asset_bundle_v3/named_assets

export type GeneratedRelic = {
  slug: string;
  name: string;
  rarity: 'Starter' | 'Common' | 'Uncommon' | 'Rare' | 'Shop' | 'Ancient';
  character: 'Neutral' | 'Ironclad' | 'Silent' | 'Regent' | 'Necrobinder' | 'Defect';
  description: string;
  image?: string;
};

export type GeneratedPotion = {
  slug: string;
  name: string;
  rarity: 'Common' | 'Uncommon' | 'Rare';
  character: 'Neutral' | 'Ironclad' | 'Silent' | 'Regent' | 'Necrobinder' | 'Defect';
  description: string;
  image?: string;
};

export const RELICS_GENERATED: GeneratedRelic[] = [
  {
    "slug": "akabeko",
    "name": "Akabeko",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of each combat, gain 8 vigor.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/akabeko.png"
  },
  {
    "slug": "alchemical_coffer",
    "name": "Alchemical Coffer",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, gain 4 potion slots filled with random potions.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/alchemical_coffer.png"
  },
  {
    "slug": "amethyst_aubergine",
    "name": "Amethyst Aubergine",
    "rarity": "Common",
    "character": "Neutral",
    "description": "enemies drop 10 additional gold.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/amethyst_aubergine.png"
  },
  {
    "slug": "anchor",
    "name": "Anchor",
    "rarity": "Common",
    "character": "Neutral",
    "description": "start each combat with 10 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/anchor.png"
  },
  {
    "slug": "arcane_scroll",
    "name": "Arcane Scroll",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, obtain a random rare card to add to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/arcane_scroll.png"
  },
  {
    "slug": "archaic_tooth",
    "name": "Archaic Tooth",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, transform a starter card with an ancient version.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/archaic_tooth.png"
  },
  {
    "slug": "art_of_war",
    "name": "Art of War",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "if you do not play any attacks during your turn, gain an additional colorless energy next turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/art_of_war.png"
  },
  {
    "slug": "astrolabe",
    "name": "Astrolabe",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, transform 3 cards, then upgrade them.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/astrolabe.png"
  },
  {
    "slug": "bag_of_marbles",
    "name": "Bag of Marbles",
    "rarity": "Common",
    "character": "Neutral",
    "description": "at the start of each combat, apply 1 vulnerable to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bag_of_marbles.png"
  },
  {
    "slug": "bag_of_preparation",
    "name": "Bag of Preparation",
    "rarity": "Common",
    "character": "Neutral",
    "description": "at the start of each combat, draw 2 additional cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bag_of_preparation.png"
  },
  {
    "slug": "beating_remnant",
    "name": "Beating Remnant",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "you cannot lose more than 20 hp in a single turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/beating_remnant.png"
  },
  {
    "slug": "beautiful_bracelet",
    "name": "Beautiful Bracelet",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, choose 3 cards in your deck. enchant them with swift 3.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/beautiful_bracelet.png"
  },
  {
    "slug": "bellows",
    "name": "Bellows",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "the first hand you draw each combat is upgraded.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bellows.png"
  },
  {
    "slug": "belt_buckle",
    "name": "Belt Buckle",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "while you have no potions, you have 2 additional dexterity.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/belt_buckle.png"
  },
  {
    "slug": "big_hat",
    "name": "Big Hat",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the start of each combat, add 2 random ethereal cards into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/big_hat.png"
  },
  {
    "slug": "biiig_hug",
    "name": "Biiig Hug",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, remove 4 cards from your deck. whenever you shuffle your draw pile, add a soot into your draw pile.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/biiig_hug.png"
  },
  {
    "slug": "black_blood",
    "name": "Black Blood",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the end of combat, heal 12 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/black_blood.png"
  },
  {
    "slug": "black_star",
    "name": "Black Star",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "elites drop an additional relic when defeated.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/black_star.png"
  },
  {
    "slug": "blessed_antler",
    "name": "Blessed Antler",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "gain colorless energy at the start of each turn. at the start of each combat, shuffle 3 dazed into your draw pile.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/blessed_antler.png"
  },
  {
    "slug": "blood_vial",
    "name": "Blood Vial",
    "rarity": "Common",
    "character": "Neutral",
    "description": "at the start of each combat, heal 2 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/blood_vial.png"
  },
  {
    "slug": "blood_soaked_rose",
    "name": "Blood-Soaked Rose",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, add 1 enthralled to your deck. gain colorless energy at the start of each turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/blood_soaked_rose.png"
  },
  {
    "slug": "bone_flute",
    "name": "Bone Flute",
    "rarity": "Common",
    "character": "Neutral",
    "description": "whenever osty attacks, gain 2 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bone_flute.png"
  },
  {
    "slug": "book_of_five_rings",
    "name": "Book of Five Rings",
    "rarity": "Common",
    "character": "Neutral",
    "description": "every 5 cards you add to your deck, heal 15 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/book_of_five_rings.png"
  },
  {
    "slug": "book_repair_knife",
    "name": "Book Repair Knife",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever a non-minion enemy dies to doom, heal 3 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/book_repair_knife.png"
  },
  {
    "slug": "bookmark",
    "name": "Bookmark",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the end of each turn, lower the cost of a random retained card by 1 until played.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bookmark.png"
  },
  {
    "slug": "booming_conch",
    "name": "Booming Conch",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of elite combats, draw 2 additional cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/booming_conch.png"
  },
  {
    "slug": "bound_phylactery",
    "name": "Bound Phylactery",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of your turn, summon 1.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bound_phylactery.png"
  },
  {
    "slug": "bowler_hat",
    "name": "Bowler Hat",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "gain 20% additional gold.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bowler_hat.png"
  },
  {
    "slug": "bread",
    "name": "Bread",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "at the start of your first turn, lose 2 energy. at the start of all other turns, gain colorless energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bread.png"
  },
  {
    "slug": "brilliant_scarf",
    "name": "Brilliant Scarf",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "the 5th card you play each turn is free.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/brilliant_scarf.png"
  },
  {
    "slug": "brimstone",
    "name": "Brimstone",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "at the start of your turn, gain 2 strength and all enemies gain 1 strength.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/brimstone.png"
  },
  {
    "slug": "bronze_scales",
    "name": "Bronze Scales",
    "rarity": "Common",
    "character": "Neutral",
    "description": "start each combat with 3 thorns.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/bronze_scales.png"
  },
  {
    "slug": "burning_blood",
    "name": "Burning Blood",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the end of combat, heal 6 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/burning_blood.png"
  },
  {
    "slug": "burning_sticks",
    "name": "Burning Sticks",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "the first time each combat you exhaust a skill, add a copy of it into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/burning_sticks.png"
  },
  {
    "slug": "calling_bell",
    "name": "Calling Bell",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, obtain a unique curse and 3 relics.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/calling_bell.png"
  },
  {
    "slug": "candelabra",
    "name": "Candelabra",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of your 2nd turn, gain 2 energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/candelabra.png"
  },
  {
    "slug": "cauldron",
    "name": "Cauldron",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "upon pickup, brews 5 random potions.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/cauldron.png"
  },
  {
    "slug": "centennial_puzzle",
    "name": "Centennial Puzzle",
    "rarity": "Common",
    "character": "Neutral",
    "description": "the first time you lose hp each combat, draw 3 cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/centennial_puzzle.png"
  },
  {
    "slug": "chandelier",
    "name": "Chandelier",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the start of your 3rd turn, gain 3 energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/chandelier.png"
  },
  {
    "slug": "chemical_x",
    "name": "Chemical X",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "the effects of your cost x cards are increased by 2.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/chemical_x.png"
  },
  {
    "slug": "choices_paradox",
    "name": "Choices Paradox",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of each combat, add 1 of 5 random cards into your hand. add retain to the chosen card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/choices_paradox.png"
  },
  {
    "slug": "claws",
    "name": "Claws",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, transform up to 6 cards into maul.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/claws.png"
  },
  {
    "slug": "cloak_clasp",
    "name": "Cloak Clasp",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the end of your turn, gain 1 block for each card in your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/cloak_clasp.png"
  },
  {
    "slug": "cracked_core",
    "name": "Cracked Core",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of each combat, channel 1 lightning.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/cracked_core.png"
  },
  {
    "slug": "crossbow",
    "name": "Crossbow",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of your turn, add a random attack into your hand. it costs 0 energy this turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/crossbow.png"
  },
  {
    "slug": "cursed_pearl",
    "name": "Cursed Pearl",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, receive greed. gain 333 gold.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/cursed_pearl.png"
  },
  {
    "slug": "data_disk",
    "name": "Data Disk",
    "rarity": "Common",
    "character": "Neutral",
    "description": "start each combat with 1 focus.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/data_disk.png"
  },
  {
    "slug": "delicate_frond",
    "name": "Delicate Frond",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of each combat, fill all empty potion slots with random potions.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/delicate_frond.png"
  },
  {
    "slug": "demon_tongue",
    "name": "Demon Tongue",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "the first time you lose hp on your turn, heal hp equal to the amount lost.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/demon_tongue.png"
  },
  {
    "slug": "diamond_diadem",
    "name": "Diamond Diadem",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "whenever you play 2 or fewer cards in a turn, take half damage from enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/diamond_diadem.png"
  },
  {
    "slug": "dingy_rug",
    "name": "Dingy Rug",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "card rewards can now contain colorless cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/dingy_rug.png"
  },
  {
    "slug": "distinguished_cape",
    "name": "Distinguished Cape",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, lose 9 max hp. add 3 apparitions to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/distinguished_cape.png"
  },
  {
    "slug": "divine_destiny",
    "name": "Divine Destiny",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of each combat, gain 6 regent star energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/divine_destiny.png"
  },
  {
    "slug": "divine_right",
    "name": "Divine Right",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of each combat, gain 3 regent star energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/divine_right.png"
  },
  {
    "slug": "dragon_fruit",
    "name": "Dragon Fruit",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "whenever you gain gold, raise your max hp by 1.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/dragon_fruit.png"
  },
  {
    "slug": "driftwood",
    "name": "Driftwood",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "you may reroll each card reward once.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/driftwood.png"
  },
  {
    "slug": "dusty_tome",
    "name": "Dusty Tome",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, obtain an ancient card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/dusty_tome.png"
  },
  {
    "slug": "ectoplasm",
    "name": "Ectoplasm",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "you can no longer gain gold. gain colorless energy at the start of each turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ectoplasm.png"
  },
  {
    "slug": "electric_shrymp",
    "name": "Electric Shrymp",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, enchant a skill with imbued.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/electric_shrymp.png"
  },
  {
    "slug": "emotion_chip",
    "name": "Emotion Chip",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "if you lost hp during the previous turn, trigger the passive ability of all orbs at the start of your turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/emotion_chip.png"
  },
  {
    "slug": "empty_cage",
    "name": "Empty Cage",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, remove 2 cards from your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/empty_cage.png"
  },
  {
    "slug": "eternal_feather",
    "name": "Eternal Feather",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "for every 5 cards in your deck, heal 3 hp whenever you enter a rest site.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/eternal_feather.png"
  },
  {
    "slug": "fencing_manual",
    "name": "Fencing Manual",
    "rarity": "Common",
    "character": "Neutral",
    "description": "at the start of each combat, forge 10.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/fencing_manual.png"
  },
  {
    "slug": "festive_popper",
    "name": "Festive Popper",
    "rarity": "Common",
    "character": "Neutral",
    "description": "at the start of each combat, deal 9 damage to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/festive_popper.png"
  },
  {
    "slug": "fiddle",
    "name": "Fiddle",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of each turn, draw 2 additional cards. you may not draw cards during your turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/fiddle.png"
  },
  {
    "slug": "frozen_egg",
    "name": "Frozen Egg",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you add a power into your deck, upgrade it.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/frozen_egg.png"
  },
  {
    "slug": "funerary_mask",
    "name": "Funerary Mask",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of each combat, add 3 souls into your draw pile.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/funerary_mask.png"
  },
  {
    "slug": "fur_coat",
    "name": "Fur Coat",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, mark 7 random combats. enemies in those rooms have 1 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/fur_coat.png"
  },
  {
    "slug": "galactic_dust",
    "name": "Galactic Dust",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "for every 10 regent star energy spent, gain 10 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/galactic_dust.png"
  },
  {
    "slug": "gambling_chip",
    "name": "Gambling Chip",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the start of each combat, discard any number of cards then draw that many.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/gambling_chip.png"
  },
  {
    "slug": "game_piece",
    "name": "Game Piece",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you play a power, draw 1 card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/game_piece.png"
  },
  {
    "slug": "ghost_seed",
    "name": "Ghost Seed",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "strikes and defends gain ethereal.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ghost_seed.png"
  },
  {
    "slug": "girya",
    "name": "Girya",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "you can now gain strength at rest sites.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/girya.png"
  },
  {
    "slug": "glass_eye",
    "name": "Glass Eye",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, obtain 2 common cards, 2 uncommon cards, and 1 rare card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/glass_eye.png"
  },
  {
    "slug": "glitter",
    "name": "Glitter",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "enchant all card rewards with glam.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/glitter.png"
  },
  {
    "slug": "gnarled_hammer",
    "name": "Gnarled Hammer",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "upon pickup, enchant up to 3 attacks with sharp 3.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/gnarled_hammer.png"
  },
  {
    "slug": "gold_plated_cables",
    "name": "Gold-Plated Cables",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "your rightmost orb triggers its passive an additional time.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/gold_plated_cables.png"
  },
  {
    "slug": "golden_compass",
    "name": "Golden Compass",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, replace the act 2 map with a single special path.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/golden_compass.png"
  },
  {
    "slug": "golden_pearl",
    "name": "Golden Pearl",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, gain 150 gold.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/golden_pearl.png"
  },
  {
    "slug": "gorget",
    "name": "Gorget",
    "rarity": "Common",
    "character": "Neutral",
    "description": "at the start of each combat, gain 4 plating.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/gorget.png"
  },
  {
    "slug": "gremlin_horn",
    "name": "Gremlin Horn",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever an enemy dies, gain colorless energy and draw 1 card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/gremlin_horn.png"
  },
  {
    "slug": "happy_flower",
    "name": "Happy Flower",
    "rarity": "Common",
    "character": "Neutral",
    "description": "every 3 turns, gain colorless energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/happy_flower.png"
  },
  {
    "slug": "helical_dart",
    "name": "Helical Dart",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you play a shiv, gain 1 dexterity this turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/helical_dart.png"
  },
  {
    "slug": "horn_cleat",
    "name": "Horn Cleat",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of your 2nd turn, gain 14 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/horn_cleat.png"
  },
  {
    "slug": "ice_cream",
    "name": "Ice Cream",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "energy is now conserved between turns.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ice_cream.png"
  },
  {
    "slug": "infused_core",
    "name": "Infused Core",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of each combat, channel 3 lightning.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/infused_core.png"
  },
  {
    "slug": "intimidating_helmet",
    "name": "Intimidating Helmet",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you play a card that costs 2 energy or more, gain 4 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/intimidating_helmet.png"
  },
  {
    "slug": "iron_club",
    "name": "Iron Club",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "every 4 cards you play, draw 1 card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/iron_club.png"
  },
  {
    "slug": "ivory_tile",
    "name": "Ivory Tile",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you play a card that costs 3 necrobinder energy or more, gain necrobinder energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ivory_tile.png"
  },
  {
    "slug": "jeweled_mask",
    "name": "Jeweled Mask",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of combat put a random power from your draw pile into your hand, it's free to play.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/jeweled_mask.png"
  },
  {
    "slug": "jewelry_box",
    "name": "Jewelry Box",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, add 1 apotheosis to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/jewelry_box.png"
  },
  {
    "slug": "joss_paper",
    "name": "Joss Paper",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every 5 times you exhaust a card, draw 1 card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/joss_paper.png"
  },
  {
    "slug": "juzu_bracelet",
    "name": "Juzu Bracelet",
    "rarity": "Common",
    "character": "Neutral",
    "description": "regular enemy combats are no longer encountered in ? rooms.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/juzu_bracelet.png"
  },
  {
    "slug": "kifuda",
    "name": "Kifuda",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "upon pickup, enchant up to 3 cards with adroit.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/kifuda.png"
  },
  {
    "slug": "kunai",
    "name": "Kunai",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "every time you play 3 attacks in a single turn, gain 1 dexterity.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/kunai.png"
  },
  {
    "slug": "kusarigama",
    "name": "Kusarigama",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every time you play 3 attacks in a single turn, deal 6 damage to a random enemy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/kusarigama.png"
  },
  {
    "slug": "lantern",
    "name": "Lantern",
    "rarity": "Common",
    "character": "Neutral",
    "description": "start each combat with an additional colorless energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lantern.png"
  },
  {
    "slug": "large_capsule",
    "name": "Large Capsule",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, obtain 2 random relics. add an additional strike and defend to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/large_capsule.png"
  },
  {
    "slug": "lasting_candy",
    "name": "Lasting Candy",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every other combat, your card rewards gain an additional power.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lasting_candy.png"
  },
  {
    "slug": "lava_lamp",
    "name": "Lava Lamp",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "at the end of combat, upgrade all card rewards if you took no damage.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lava_lamp.png"
  },
  {
    "slug": "lava_rock",
    "name": "Lava Rock",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "the act 1 boss drops 2 relics.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lava_rock.png"
  },
  {
    "slug": "lead_paperweight",
    "name": "Lead Paperweight",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, choose 1 of 2 colorless cards to add to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lead_paperweight.png"
  },
  {
    "slug": "leafy_poultice",
    "name": "Leafy Poultice",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, transform 1 of your strikes and 1 of your defends and lose 10 max hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/leafy_poultice.png"
  },
  {
    "slug": "letter_opener",
    "name": "Letter Opener",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every time you play 3 skills in a single turn, deal 5 damage to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/letter_opener.png"
  },
  {
    "slug": "lizard_tail",
    "name": "Lizard Tail",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "when you would die, heal to 50% of your max hp instead.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lizard_tail.png"
  },
  {
    "slug": "looming_fruit",
    "name": "Looming Fruit",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, raise your max hp by 31.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/looming_fruit.png"
  },
  {
    "slug": "lost_coffer",
    "name": "Lost Coffer",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, gain 1 card reward and procure 1 random potion.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lost_coffer.png"
  },
  {
    "slug": "lucky_fysh",
    "name": "Lucky Fysh",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever you add a card to your deck, gain 15 gold.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lucky_fysh.png"
  },
  {
    "slug": "lunar_pastry",
    "name": "Lunar Pastry",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the end of your turn, gain regent star energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/lunar_pastry.png"
  },
  {
    "slug": "mango",
    "name": "Mango",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "upon pickup, raise your max hp by 14.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/mango.png"
  },
  {
    "slug": "massive_scroll",
    "name": "Massive Scroll",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, choose 1 of 3 multiplayer colorless cards to add to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/massive_scroll.png"
  },
  {
    "slug": "meal_ticket",
    "name": "Meal Ticket",
    "rarity": "Common",
    "character": "Neutral",
    "description": "whenever you enter a shop room, heal 15 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/meal_ticket.png"
  },
  {
    "slug": "meat_cleaver",
    "name": "Meat Cleaver",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "you may cook at rest sites.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/meat_cleaver.png"
  },
  {
    "slug": "meat_on_the_bone",
    "name": "Meat on the Bone",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "if your hp is at or below 50% at the end of combat, heal 12 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/meat_on_the_bone.png"
  },
  {
    "slug": "membership_card",
    "name": "Membership Card",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "50% discount on all products!",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/membership_card.png"
  },
  {
    "slug": "mercury_hourglass",
    "name": "Mercury Hourglass",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of your turn, deal 3 damage to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/mercury_hourglass.png"
  },
  {
    "slug": "metronome",
    "name": "Metronome",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "the first time you channel 7 orbs each combat, deal 30 damage to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/metronome.png"
  },
  {
    "slug": "mini_regent",
    "name": "Mini Regent",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "the first time you spend regent star energy each turn, gain 1 strength.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/mini_regent.png"
  },
  {
    "slug": "miniature_cannon",
    "name": "Miniature Cannon",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "upgraded attacks deal 3 additional damage.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/miniature_cannon.png"
  },
  {
    "slug": "miniature_tent",
    "name": "Miniature Tent",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "you may choose any number of options at rest sites.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/miniature_tent.png"
  },
  {
    "slug": "molten_egg",
    "name": "Molten Egg",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you add an attack card to your deck, upgrade it.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/molten_egg.png"
  },
  {
    "slug": "mummified_hand",
    "name": "Mummified Hand",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you play a power, a random card in your hand is free to play that turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/mummified_hand.png"
  },
  {
    "slug": "music_box",
    "name": "Music Box",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "create an ethereal copy of the first attack you play each turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/music_box.png"
  },
  {
    "slug": "mystic_lighter",
    "name": "Mystic Lighter",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "enchanted attacks deal 9 additional damage.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/mystic_lighter.png"
  },
  {
    "slug": "new_leaf",
    "name": "New Leaf",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, transform 1 card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/new_leaf.png"
  },
  {
    "slug": "ninja_scroll",
    "name": "Ninja Scroll",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "at the start of each combat, add 3 shivs into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ninja_scroll.png"
  },
  {
    "slug": "nunchaku",
    "name": "Nunchaku",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every time you play 10 attacks, gain colorless energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/nunchaku.png"
  },
  {
    "slug": "nutritious_oyster",
    "name": "Nutritious Oyster",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, raise your max hp by 11.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/nutritious_oyster.png"
  },
  {
    "slug": "nutritious_soup",
    "name": "Nutritious Soup",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, enchant all strikes in your deck with tezcatara's ember.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/nutritious_soup.png"
  },
  {
    "slug": "oddly_smooth_stone",
    "name": "Oddly Smooth Stone",
    "rarity": "Common",
    "character": "Neutral",
    "description": "start each combat with 1 dexterity.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/oddly_smooth_stone.png"
  },
  {
    "slug": "old_coin",
    "name": "Old Coin",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "upon pickup, gain 300 gold.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/old_coin.png"
  },
  {
    "slug": "orange_dough",
    "name": "Orange Dough",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the start of each combat, add 2 random colorless cards into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/orange_dough.png"
  },
  {
    "slug": "orichalcum",
    "name": "Orichalcum",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "if you end your turn without block, gain 6 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/orichalcum.png"
  },
  {
    "slug": "ornamental_fan",
    "name": "Ornamental Fan",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every time you play 3 attacks in a single turn, gain 4 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ornamental_fan.png"
  },
  {
    "slug": "orrery",
    "name": "Orrery",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "upon pickup, gain 5 card rewards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/orrery.png"
  },
  {
    "slug": "pantograph",
    "name": "Pantograph",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of each boss combat, heal 25 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/pantograph.png"
  },
  {
    "slug": "paper_krane",
    "name": "Paper Krane",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "enemies with weak deal 40% less damage to you rather than 25%.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/paper_krane.png"
  },
  {
    "slug": "paper_phrog",
    "name": "Paper Phrog",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "enemies with vulnerable take 75% more damage rather than 50%.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/paper_phrog.png"
  },
  {
    "slug": "parrying_shield",
    "name": "Parrying Shield",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "if you end a turn with at least 10 block, deal 6 damage to a random enemy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/parrying_shield.png"
  },
  {
    "slug": "pear",
    "name": "Pear",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "upon pickup, raise your max hp by 10.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/pear.png"
  },
  {
    "slug": "pen_nib",
    "name": "Pen Nib",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every 10th attack you play deals double damage.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/pen_nib.png"
  },
  {
    "slug": "pendulum",
    "name": "Pendulum",
    "rarity": "Common",
    "character": "Neutral",
    "description": "every 3 turns, draw a card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/pendulum.png"
  },
  {
    "slug": "permafrost",
    "name": "Permafrost",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "the first time you play a power each combat, gain 6 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/permafrost.png"
  },
  {
    "slug": "petrified_toad",
    "name": "Petrified Toad",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of each combat, procure a potion-shaped rock.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/petrified_toad.png"
  },
  {
    "slug": "phylactery_unbound",
    "name": "Phylactery Unbound",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of each combat, summon 5. at the start of your turn, summon 2.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/phylactery_unbound.png"
  },
  {
    "slug": "planisphere",
    "name": "Planisphere",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever you enter a ? room, heal 4 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/planisphere.png"
  },
  {
    "slug": "pocketwatch",
    "name": "Pocketwatch",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you play 3 or fewer cards during your turn, draw 3 additional cards at the start of your next turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/pocketwatch.png"
  },
  {
    "slug": "pomander",
    "name": "Pomander",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, upgrade a card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/pomander.png"
  },
  {
    "slug": "potion_belt",
    "name": "Potion Belt",
    "rarity": "Common",
    "character": "Neutral",
    "description": "upon pickup, gain 2 potion slots.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/potion_belt.png"
  },
  {
    "slug": "power_cell",
    "name": "Power Cell",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the start of each combat, add 2 zero-cost cards from your draw pile into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/power_cell.png"
  },
  {
    "slug": "prayer_wheel",
    "name": "Prayer Wheel",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "normal enemies drop an additional card reward.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/prayer_wheel.png"
  },
  {
    "slug": "precarious_shears",
    "name": "Precarious Shears",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, remove 2 cards from your deck and take 13 damage.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/precarious_shears.png"
  },
  {
    "slug": "precise_scissors",
    "name": "Precise Scissors",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, remove 1 card from your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/precise_scissors.png"
  },
  {
    "slug": "preserved_fog",
    "name": "Preserved Fog",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, remove 5 cards from your deck. add folly to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/preserved_fog.png"
  },
  {
    "slug": "prismatic_gem",
    "name": "Prismatic Gem",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "gain colorless energy at the start of each turn. card rewards now contain cards from other colors.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/prismatic_gem.png"
  },
  {
    "slug": "pumpkin_candle",
    "name": "Pumpkin Candle",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "gain colorless energy at the start of each turn. extinguishes at the start of act 3.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/pumpkin_candle.png"
  },
  {
    "slug": "punch_dagger",
    "name": "Punch Dagger",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "upon pickup, enchant an attack with momentum 5.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/punch_dagger.png"
  },
  {
    "slug": "radiant_pearl",
    "name": "Radiant Pearl",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of each combat, add 1 luminesce into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/radiant_pearl.png"
  },
  {
    "slug": "rainbow_ring",
    "name": "Rainbow Ring",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "the first time you play an attack, skill, and power each turn, gain 1 strength and 1 dexterity.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/rainbow_ring.png"
  },
  {
    "slug": "razor_tooth",
    "name": "Razor Tooth",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "every time you play an attack or skill, upgrade it for the remainder of combat.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/razor_tooth.png"
  },
  {
    "slug": "red_mask",
    "name": "Red Mask",
    "rarity": "Common",
    "character": "Neutral",
    "description": "at the start of each combat, apply 1 weak to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/red_mask.png"
  },
  {
    "slug": "red_skull",
    "name": "Red Skull",
    "rarity": "Common",
    "character": "Neutral",
    "description": "while your hp is at or below 50%, you have 3 additional strength.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/red_skull.png"
  },
  {
    "slug": "regal_pillow",
    "name": "Regal Pillow",
    "rarity": "Common",
    "character": "Neutral",
    "description": "whenever you rest, heal an additional 15 hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/regal_pillow.png"
  },
  {
    "slug": "regalite",
    "name": "Regalite",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever you create a colorless card, gain 2 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/regalite.png"
  },
  {
    "slug": "reptile_trinket",
    "name": "Reptile Trinket",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever you use a potion, gain 3 strength this turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/reptile_trinket.png"
  },
  {
    "slug": "ring_of_the_drake",
    "name": "Ring of the Drake",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of your first 3 turns, draw 2 additional cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ring_of_the_drake.png"
  },
  {
    "slug": "ring_of_the_snake",
    "name": "Ring of the Snake",
    "rarity": "Starter",
    "character": "Neutral",
    "description": "at the start of each combat, draw 2 additional cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ring_of_the_snake.png"
  },
  {
    "slug": "ringing_triangle",
    "name": "Ringing Triangle",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "retain your hand on the first turn of combat.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ringing_triangle.png"
  },
  {
    "slug": "ripple_basin",
    "name": "Ripple Basin",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "if you did not play any attacks during your turn, gain 4 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ripple_basin.png"
  },
  {
    "slug": "royal_stamp",
    "name": "Royal Stamp",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "upon pickup, choose an attack or skill in your deck to enchant with royally approved.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/royal_stamp.png"
  },
  {
    "slug": "ruined_helmet",
    "name": "Ruined Helmet",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "the first time you gain strength each combat, double the amount gained.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/ruined_helmet.png"
  },
  {
    "slug": "runic_capacitor",
    "name": "Runic Capacitor",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "start each combat with 3 additional orb slots.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/runic_capacitor.png"
  },
  {
    "slug": "runic_pyramid",
    "name": "Runic Pyramid",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the end of your turn, you no longer discard your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/runic_pyramid.png"
  },
  {
    "slug": "sai",
    "name": "Sai",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of your turn, gain 7 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sai.png"
  },
  {
    "slug": "sand_castle",
    "name": "Sand Castle",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, upgrade 6 random cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sand_castle.png"
  },
  {
    "slug": "screaming_flagon",
    "name": "Screaming Flagon",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "if you end your turn with no cards in your hand, deal 20 damage to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/screaming_flagon.png"
  },
  {
    "slug": "scroll_boxes",
    "name": "Scroll Boxes",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, lose all gold and choose 1 of 2 packs of cards to add to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/scroll_boxes.png"
  },
  {
    "slug": "sea_glass",
    "name": "Sea Glass",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "see 15 cards from another character. choose any number of them to add to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sea_glass.png"
  },
  {
    "slug": "seal_of_gold",
    "name": "Seal of Gold",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of your turn, spend 5 gold to gain colorless energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/seal_of_gold.png"
  },
  {
    "slug": "self_forming_clay",
    "name": "Self-Forming Clay",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever you lose hp in combat, gain 3 block next turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/self_forming_clay.png"
  },
  {
    "slug": "sere_talon",
    "name": "Sere Talon",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, add 2 random curses and 3 wishes to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sere_talon.png"
  },
  {
    "slug": "shovel",
    "name": "Shovel",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "you can now dig at rest sites to obtain a random relic.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/shovel.png"
  },
  {
    "slug": "shuriken",
    "name": "Shuriken",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "every time you play 3 attacks in a single turn, gain 1 strength.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/shuriken.png"
  },
  {
    "slug": "signet_ring",
    "name": "Signet Ring",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, gain 999 gold.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/signet_ring.png"
  },
  {
    "slug": "silver_crucible",
    "name": "Silver Crucible",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "the first 3 card rewards you see are upgraded. the first treasure chest you open is empty.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/silver_crucible.png"
  },
  {
    "slug": "sling_of_courage",
    "name": "Sling of Courage",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "start each elite combat with 2 strength.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sling_of_courage.png"
  },
  {
    "slug": "small_capsule",
    "name": "Small Capsule",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, obtain a random relic.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/small_capsule.png"
  },
  {
    "slug": "snecko_eye",
    "name": "Snecko Eye",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of your turn, draw 2 additional cards. start each combat confused.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/snecko_eye.png"
  },
  {
    "slug": "snecko_skull",
    "name": "Snecko Skull",
    "rarity": "Common",
    "character": "Neutral",
    "description": "whenever you apply poison, apply an additional 1 poison.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/snecko_skull.png"
  },
  {
    "slug": "sozu",
    "name": "Sozu",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "gain colorless energy at the start of each turn. you can no longer obtain potions.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sozu.png"
  },
  {
    "slug": "sparkling_rouge",
    "name": "Sparkling Rouge",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of your 3rd turn, gain 1 strength and 1 dexterity.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sparkling_rouge.png"
  },
  {
    "slug": "spiked_gauntlets",
    "name": "Spiked Gauntlets",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "gain colorless energy at the start of each turn. powers cost 1 more colorless energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/spiked_gauntlets.png"
  },
  {
    "slug": "stone_calendar",
    "name": "Stone Calendar",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the end of turn 7, deal 52 damage to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/stone_calendar.png"
  },
  {
    "slug": "stone_cracker",
    "name": "Stone Cracker",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of boss combats, upgrade 3 random cards in your draw pile for the rest of combat.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/stone_cracker.png"
  },
  {
    "slug": "stone_humidifier",
    "name": "Stone Humidifier",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "whenever you rest at a rest site, raise your max hp by 5.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/stone_humidifier.png"
  },
  {
    "slug": "storybook",
    "name": "Storybook",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, add 1 brightest flame to your deck.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/storybook.png"
  },
  {
    "slug": "strawberry",
    "name": "Strawberry",
    "rarity": "Common",
    "character": "Neutral",
    "description": "upon pickup, raise your max hp by 7.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/strawberry.png"
  },
  {
    "slug": "strike_dummy",
    "name": "Strike Dummy",
    "rarity": "Common",
    "character": "Neutral",
    "description": "cards containing &#34;strike&#34; deal 3 additional damage.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/strike_dummy.png"
  },
  {
    "slug": "sturdy_clamp",
    "name": "Sturdy Clamp",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "up to 10 block persists across turns.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/sturdy_clamp.png"
  },
  {
    "slug": "symbiotic_virus",
    "name": "Symbiotic Virus",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of each combat, channel 1 dark.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/symbiotic_virus.png"
  },
  {
    "slug": "the_abacus",
    "name": "The Abacus",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "whenever you shuffle your draw pile, gain 6 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/the_abacus.png"
  },
  {
    "slug": "the_courier",
    "name": "The Courier",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "the merchant no longer runs out of cards, relics, or potions and his prices are reduced by 20%.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/the_courier.png"
  },
  {
    "slug": "throwing_axe",
    "name": "Throwing Axe",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "the first card you play each combat is played an extra time.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/throwing_axe.png"
  },
  {
    "slug": "tingsha",
    "name": "Tingsha",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever you discard a card during your turn, deal 3 damage to a random enemy for each card discarded.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/tingsha.png"
  },
  {
    "slug": "tiny_mailbox",
    "name": "Tiny Mailbox",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "whenever you rest, procure 2 random potions.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/tiny_mailbox.png"
  },
  {
    "slug": "toasty_mittens",
    "name": "Toasty Mittens",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "at the start of your turn, exhaust the top card of your draw pile and gain 1 strength.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/toasty_mittens.png"
  },
  {
    "slug": "toolbox",
    "name": "Toolbox",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "at the start of each combat, choose 1 of 3 random colorless cards and add the chosen card into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/toolbox.png"
  },
  {
    "slug": "touch_of_orobas",
    "name": "Touch of Orobas",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, replace your starter relic with an ancient version.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/touch_of_orobas.png"
  },
  {
    "slug": "tough_bandages",
    "name": "Tough Bandages",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you discard a card during your turn, gain 3 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/tough_bandages.png"
  },
  {
    "slug": "toxic_egg",
    "name": "Toxic Egg",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you add a skill into your deck, upgrade it.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/toxic_egg.png"
  },
  {
    "slug": "toy_box",
    "name": "Toy Box",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "upon pickup, obtain 4 wax relics. every 3 combats, your left-most wax relic will melt away.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/toy_box.png"
  },
  {
    "slug": "tri_boomerang",
    "name": "Tri-Boomerang",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "choose 3 attacks in your deck. enchant them with instinct.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/tri_boomerang.png"
  },
  {
    "slug": "tungsten_rod",
    "name": "Tungsten Rod",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you would lose hp, lose 1 less.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/tungsten_rod.png"
  },
  {
    "slug": "tuning_fork",
    "name": "Tuning Fork",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "every time you play 10 skills, gain 7 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/tuning_fork.png"
  },
  {
    "slug": "twisted_funnel",
    "name": "Twisted Funnel",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "at the start of each combat, apply 4 poison to all enemies.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/twisted_funnel.png"
  },
  {
    "slug": "unceasing_top",
    "name": "Unceasing Top",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "whenever you have no cards in hand during your turn, draw a card.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/unceasing_top.png"
  },
  {
    "slug": "undying_sigil",
    "name": "Undying Sigil",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "enemies with at least as much doom as hp deal 50% less damage.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/undying_sigil.png"
  },
  {
    "slug": "unsettling_lamp",
    "name": "Unsettling Lamp",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "each combat, the first time you play a card that debuffs an enemy, double its effect.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/unsettling_lamp.png"
  },
  {
    "slug": "vajra",
    "name": "Vajra",
    "rarity": "Common",
    "character": "Neutral",
    "description": "start each combat with 1 strength.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/vajra.png"
  },
  {
    "slug": "vambrace",
    "name": "Vambrace",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "the first time you gain block from a card each combat, double the amount gained.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/vambrace.png"
  },
  {
    "slug": "velvet_choker",
    "name": "Velvet Choker",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "gain colorless energy at the start of each turn. you cannot play more than 6 cards per turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/velvet_choker.png"
  },
  {
    "slug": "venerable_tea_set",
    "name": "Venerable Tea Set",
    "rarity": "Common",
    "character": "Neutral",
    "description": "whenever you enter a rest site, start the next combat with an additional 2 energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/venerable_tea_set.png"
  },
  {
    "slug": "very_hot_cocoa",
    "name": "Very Hot Cocoa",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "start each combat with an additional 4 energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/very_hot_cocoa.png"
  },
  {
    "slug": "vexing_puzzlebox",
    "name": "Vexing Puzzlebox",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "at the start of each combat, add a random card into your hand. it's free to play this turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/vexing_puzzlebox.png"
  },
  {
    "slug": "vitruvian_minion",
    "name": "Vitruvian Minion",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "cards containing &#34;minion&#34; deal double damage and gain double block.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/vitruvian_minion.png"
  },
  {
    "slug": "war_hammer",
    "name": "War Hammer",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "whenever you kill an elite, upgrade 4 random cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/war_hammer.png"
  },
  {
    "slug": "war_paint",
    "name": "War Paint",
    "rarity": "Common",
    "character": "Neutral",
    "description": "upon pickup, upgrade 2 random skills.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/war_paint.png"
  },
  {
    "slug": "whetstone",
    "name": "Whetstone",
    "rarity": "Common",
    "character": "Neutral",
    "description": "upon pickup, upgrade 2 random attacks.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/whetstone.png"
  },
  {
    "slug": "whispering_earring",
    "name": "Whispering Earring",
    "rarity": "Ancient",
    "character": "Neutral",
    "description": "gain colorless energy at the start of each turn. vakuu plays your first turn for you.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/whispering_earring.png"
  },
  {
    "slug": "white_beast_statue",
    "name": "White Beast Statue",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "potions always appear in combat rewards.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/white_beast_statue.png"
  },
  {
    "slug": "white_star",
    "name": "White Star",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "elites drop an additional rare card reward.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/white_star.png"
  },
  {
    "slug": "wing_charm",
    "name": "Wing Charm",
    "rarity": "Shop",
    "character": "Neutral",
    "description": "a random card in each card reward is enchanted with swift 1.",
    "image": "https://assets.sts2guide.com/assets/sts2/relics-v20260310-wiki-r1/wing_charm.png"
  }
] as GeneratedRelic[];

export const POTIONS_GENERATED: GeneratedPotion[] = [
  {
    "slug": "ashwater",
    "name": "Ashwater",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "exhaust any number of cards in your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/ashwater.png"
  },
  {
    "slug": "attack_potion",
    "name": "Attack Potion",
    "rarity": "Common",
    "character": "Neutral",
    "description": "choose 1 of 3 random attack cards to add into your hand. it's free to play this turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/attack_potion.png"
  },
  {
    "slug": "beetle_juice",
    "name": "Beetle Juice",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "enemy's attacks deal 30% less damage for the next 4 turns.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/beetle_juice.png"
  },
  {
    "slug": "blessing_of_the_forge",
    "name": "Blessing of the Forge",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "upgrade all cards in your hand for the rest of combat.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/blessing_of_the_forge.png"
  },
  {
    "slug": "block_potion",
    "name": "Block Potion",
    "rarity": "Common",
    "character": "Neutral",
    "description": "gain 12 block.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/block_potion.png"
  },
  {
    "slug": "blood_potion",
    "name": "Blood Potion",
    "rarity": "Common",
    "character": "Neutral",
    "description": "heal for 20% of your max hp.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/blood_potion.png"
  },
  {
    "slug": "bone_brew",
    "name": "Bone Brew",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "summon 15.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/bone_brew.png"
  },
  {
    "slug": "bottled_potential",
    "name": "Bottled Potential",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "shuffle all your cards into your draw pile. draw 5 cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/bottled_potential.png"
  },
  {
    "slug": "colorless_potion",
    "name": "Colorless Potion",
    "rarity": "Common",
    "character": "Neutral",
    "description": "choose 1 of 3 random colorless cards to add into your hand. it's free to play this turn.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/colorless_potion.png"
  },
  {
    "slug": "cosmic_concoction",
    "name": "Cosmic Concoction",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "add 3 upgraded colorless cards into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/cosmic_concoction.png"
  },
  {
    "slug": "cunning_potion",
    "name": "Cunning Potion",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "add 3 upgraded shivs into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/cunning_potion.png"
  },
  {
    "slug": "cure_all",
    "name": "Cure All",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "gain colorless energy. draw 2 cards.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/cure_all.png"
  },
  {
    "slug": "dexterity_potion",
    "name": "Dexterity Potion",
    "rarity": "Common",
    "character": "Neutral",
    "description": "gain 2 dexterity.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/dexterity_potion.png"
  },
  {
    "slug": "distilled_chaos",
    "name": "Distilled Chaos",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "play the top 3 cards of your draw pile.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/distilled_chaos.png"
  },
  {
    "slug": "droplet_of_precognition",
    "name": "Droplet of Precognition",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "choose a card in your draw pile and add it into your hand.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/droplet_of_precognition.png"
  },
  {
    "slug": "duplicator",
    "name": "Duplicator",
    "rarity": "Uncommon",
    "character": "Neutral",
    "description": "this turn, your next card is played an extra time.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/duplicator.png"
  },
  {
    "slug": "energy_potion",
    "name": "Energy Potion",
    "rarity": "Common",
    "character": "Neutral",
    "description": "gain colorless energy colorless energy.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/energy_potion.png"
  },
  {
    "slug": "entropic_brew",
    "name": "Entropic Brew",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "fill all your empty potion slots with random potions.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/entropic_brew.png"
  },
  {
    "slug": "essence_of_darkness",
    "name": "Essence of Darkness",
    "rarity": "Rare",
    "character": "Neutral",
    "description": "channel a dark for each of your orb slots.",
    "image": "https://assets.sts2guide.com/assets/sts2/potions-v20260310-wiki-r1/essence_of_darkness.png"
  }
] as GeneratedPotion[];
